theme: jekyll-theme-hacker
url: https://eriksoriano.github.io

baseurl: /jkassignment/
title: index page (home)
description: jerkyll page bro

# custom variables can be added too

# site variable
# instagram: "https://instagram.com/erik"
# [instagram]{{site.instagram}} 

# page varaiable
# [instagram]{{page.instagram}} 

author: erik soriano
